### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by OscarDeDios**
Hi Francois, I've added a spanish translation.

Regards.
Oscar.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Thank you really much Oscar!
That is much appreciated.

In order to easily keep track of translations, we've decided to remove the `description` fields and only translate `message` keys. See https://github.com/beaufortfrancois/extensions-update-notifier-chrome-extension/blob/master/src/_locales/fr/messages.json for instance.

Do you mind removing the "description" keys so that I can merge your pull request?

**Comment by OscarDeDios** [comment]
Hi, you are welcome, I like this extension.

I've removed the descriptions, good idea it's not necesary.

Regards.
Oscar.

**Comment by beaufortfrancois** [comment]
I just updated WebStore with your patch: https://chrome.google.com/webstore/detail/extensions-update-notifie/nlldbplhbaopldicmcoogopmkonpebjm

Thank you Oscar!
Have a good day!

**Comment by OscarDeDios** [comment]
Great.
Have a good day!

**Pull request merged**
